name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Showing PWD and List files
        run: |
          pwd
          ls -a
      - name: Using Checkout
        uses: actions/checkout@v1
      - name: Showing PWD and List files with checkout
        run: |
          pwd
          ls -a
      - name: Simple Action jobs
        uses: actions/hello-world-javascript-action@v1
        id: greet
        with:
          who-to-greet: Victor
      - name: Get time from step 
        run: echo "${{ steps.greet.outputs.time }}"
