name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Action jobs
        uses: actions/hello-world-javascript-actions@v1
        with:
          who-to-geet: Victor
          